In [63]:
import math
def func(rho, i, n): 
    print(f"rho = {rho}\ti = {i}\tn = {n}")
    epsilon_0 = 5*1e-3 
    lr = 5*1e-3 
    
    eta = 1 - (2* rho**2 * math.log(1/epsilon_0))/n  
    a = rho  
    b = -2
    c = 2/i * math.log2(n/(n - 2*(rho**2)*math.log(1/epsilon_0)))

    # calculate the discriminant
    d = (b**2) - (4*a*c)

    # find two solutions
    sol1 = (-b-math.sqrt(d))/(2*a)
    sol2 = (-b+math.sqrt(d))/(2*a)
    
    # print('The solution are {0} and {1}'.format(sol1,sol2))
    
    gamma_cv1 = sol1/lr
    gamma_cv2 = sol2/lr

    print('eta = {0}\tgamma_cv are {1} and {2}'.format(eta,gamma_cv1,gamma_cv2))

func(rho=1.4, i=30, n=100)
func(rho=1.4, i=20, n=100)
func(rho=1.1, i=30, n=100)
func(rho=1.05, i=30, n=100)

rho = 1.4	i = 30	n = 100
eta = 0.7923059592313171	gamma_cv are 2.2569648939844305 and 283.4573208203013
rho = 1.4	i = 20	n = 100
eta = 0.7923059592313171	gamma_cv are 3.3991440465523146 and 282.3151416677334
rho = 1.1	i = 30	n = 100
eta = 0.8717807197295375	gamma_cv are 1.3245768685607398 and 362.31178676780286
rho = 1.05	i = 30	n = 100
eta = 0.8831721020676158	gamma_cv are 1.1986615349025511 and 379.7537194174784


In [31]:
import numpy as np 

a1 = -0.5; b1 = 272 
a2 = 1; b2 = -28 

x = (b2 - b1)/(a1 - a2)
y = a1 * x + b1 

print(f"x = {x} y = {y}")

x = 200.0 y = 172.0


In [5]:
import torch 
import copy 

from torch import nn 

model = nn.Linear(1, 1)
model_cp = copy.deepcopy(model)

model.to('cuda:0')

torch.cuda.current_device()
torch.cuda.is_available()

True

In [9]:
model.to('cpu')
torch.cuda.current_device()
torch.cuda.device_count()

torch.cuda.device(0)
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Ti'

In [14]:
# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')

model.to(device)

# check whether the current device on cuda 
print(next(model.parameters()).is_cuda)

model.to('cpu')
# check whether the current device on cude 
print(next(model.parameters()).is_cuda)



Using device: cuda

NVIDIA GeForce RTX 3060 Ti
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
True
False


In [3]:
from copy import deepcopy 
import torch 

x = torch.ones((1, ), device=torch.device("cuda", 0))
print(x)
y = deepcopy(x)
print(y)

tensor([1.], device='cuda:0')
tensor([1.], device='cuda:0')


In [2]:
def to_times(x_dB): 
    return 10 ** (x_dB/10)

bw_dB = 60 # 1MHz bandwidth
bw = to_times(bw_dB)
bw

1000000.0

In [5]:
to_times(-174+bw_dB-30)

3.9810717055349695e-15

In [4]:
import numpy as np 

eta = np.arange(0.01, 1, 0.1)
np.log2(1/eta)

array([6.64385619, 3.18442457, 2.25153877, 1.68965988, 1.28630419,
       0.97143085, 0.71311885, 0.49410907, 0.30400619, 0.13606155])

In [5]:
v = 3 
v * np.log2(1/eta)

array([19.93156857,  9.55327371,  6.7546163 ,  5.06897964,  3.85891256,
        2.91429254,  2.13935656,  1.48232721,  0.91201856,  0.40818465])

In [6]:
L_Lipschitz = 0.0630
delta_lr = 0.01
gamma_cv = 1e-3

v = 2 / ((2 - L_Lipschitz * delta_lr) * gamma_cv * delta_lr)
v

100031.50992562655

In [7]:
import numpy as np 

xi_factor = 1 
epsilon_0 = 1e-2 

a_0 = 2 * (L_Lipschitz**2) / ((gamma_cv**2) * xi_factor) * np.log(1 / (epsilon_0))
a_0 / (1 - eta)

array([ 36925.09185492,  41073.97858019,  46273.21637516,  52979.47961793,
        61959.05243453,  74603.75701301,  93732.92547788, 126054.62391853,
       192399.16282302, 406176.01040415])

In [ ]:
(1 / (epsilon_0))
a_0 / (1 - eta)

In [13]:

eta = np.arange(0.0, 1.01, 0.1)
eta

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [17]:
1 - (1- eta) * (gamma_cv **2) * xi_factor / (2 * L_Lipschitz ** 2) 

array([0.82294259, 0.84064833, 0.85835407, 0.87605981, 0.89376555,
       0.9114713 , 0.92917704, 0.94688278, 0.96458852, 0.98229426,
       1.        ])

In [16]:
(gamma_cv **2) * xi_factor / (2 * L_Lipschitz ** 2) 

0.1770574092752425

In [3]:
import numpy as np 

a = np.array([1, 2, 3, 4])
a[:-1]


array([1, 2, 3])