In [4]:
import torch.nn as nn 

model = nn.Linear(2, 3)
params = {k: v.data for k, v in zip(model.state_dict(), model.parameters())}

print(params)
# Calculate the number of parameters 
num_params = sum(param.numel() for param in model.parameters())
print(num_params) # 9 

{'weight': tensor([[-0.0754, -0.0753],
        [-0.6765,  0.5025],
        [-0.2202,  0.6343]]), 'bias': tensor([-0.2950, -0.1803, -0.6243])}
9


In [5]:
import numpy as np 

model1 = nn.Linear(2, 3)
model2 = nn.Linear(2, 3)
model3 = nn.Linear(2, 3)

# Copy model.parameters() to flatten np.array 
def preprocess(model): 
    params = np.array([])
    for v in model.parameters(): 
        params = np.append(params, v.data.numpy())
    return params 

params1 = preprocess(model1)
params2 = preprocess(model2)
params3 = preprocess(model3)

# Avarage (aggregate) the model parameters 
params = np.mean(np.array([params1, params2, params3]), axis=0)
print(params)

# Convert the data back to dictionary of parameters 
params_dict = {}

# load_state_dict ()
# https://pytorch.org/tutorials/beginner/saving_loading_models.html


[-0.01657281 -0.01304539 -0.41262166 -0.12366266  0.03107857 -0.12102356
 -0.0534808  -0.03138488 -0.1824799 ]


In [6]:
c = {'a': 1, 'b': 2, 'c': 3}
d = {}

for k in c.keys(): 
    d[k] = c[k]

print(d)

{'a': 1, 'b': 2, 'c': 3}


In [7]:
x1 = 10 ** (-5)
x2 = 1e-5

print("x1 =", x1)
print("x2 =", x2)

x1 = 1e-05
x2 = 1e-05


In [8]:
from math import exp
from scipy.special import lambertw

t = lambertw(1/(2 * exp(1)))
x = t.real + 1
print(x)


1.157184951483814


In [9]:
import numpy as np 
arr = np.array([5, -1, 2, 4, 2, 3, 7, 0, -1, -4, -3])
k = 5 

idx = np.argpartition(arr, k)[:k]
print(idx)


print(idx[np.where(arr[idx] < 0)])

decs = np.zeros_like(arr)
decs[idx] = 1
print(decs)

[10  9  1  8  7]
[10  9  1  8]
[0 1 0 0 0 0 0 1 1 1 1]


In [3]:
from scipy.special import lambertw
import numpy as np 

tmp = lambertw(1 / (2 * np.exp(1))).real

t = 1 + tmp 
print(t)

t2 = 2 * np.exp(tmp)
print(t2)

t3 = lambertw(-1/(2 * np.exp(1)))
print(f"t3 = {t3}")

t4 = lambertw(-1/(2 * np.exp(1)), k=-1)
print(f"t4 = {t4}")


t4 = (2 * np.exp(t3 + 1) - 1)
print(t4)

1.157184951483814
2.3404240526760884
t3 = (-0.23196095298653444+0j)
t4 = (-2.6783469900166605+0j)
(3.3110704070010053+0j)


In [2]:
import math
import numpy as np 

idx = np.array([i for i in range(1, 10, 1)], dtype=int)
print(idx)
# h_uav = np.zeros_like(idx)
# h_bs = np.zeros_like(idx)
v = 23 

for i in idx:
    eta = 0.1 * i
    x = ((1 - eta)/ (eta * math.log(1 / eta)) - 1) * v / math.log(2)
    h_uav = 2.7 * 1e-11 / x 
    h_bs = 4.38 * 1e-11 / x 
    print("eta = {:.1f}\tx = {:.3f}\th_uav = {:.3e}\t h_bs = {:.3e}".format(eta, x, h_uav, h_bs))

[1 2 3 4 5 6 7 8 9]
eta = 0.1	x = 96.515	h_uav = 2.797e-13	 h_bs = 4.538e-13
eta = 0.2	x = 49.287	h_uav = 5.478e-13	 h_bs = 8.887e-13
eta = 0.3	x = 31.126	h_uav = 8.675e-13	 h_bs = 1.407e-12
eta = 0.4	x = 21.138	h_uav = 1.277e-12	 h_bs = 2.072e-12
eta = 0.5	x = 14.690	h_uav = 1.838e-12	 h_bs = 2.982e-12
eta = 0.6	x = 10.123	h_uav = 2.667e-12	 h_bs = 4.327e-12
eta = 0.7	x = 6.689	h_uav = 4.037e-12	 h_bs = 6.548e-12
eta = 0.8	x = 3.994	h_uav = 6.761e-12	 h_bs = 1.097e-11
eta = 0.9	x = 1.811	h_uav = 1.491e-11	 h_bs = 2.418e-11


In [21]:
import numpy as np 

uav_gains = np.random.randint(0, 10, 5)
bs_gains = np.random.randint(0, 10, 5)

print(uav_gains)
print(bs_gains)
decs = 0

gains = decs * uav_gains + (1 - decs) * bs_gains
print(gains)

[8 2 8 7 3]
[5 0 4 5 3]
[5 0 4 5 3]


In [19]:
import numpy as np 

uav_gains = np.random.randint(0, 100, 1000)
bs_gains = np.random.randint(0, 100, 1000)

decs = np.random.randint(0, 2, 1000, dtype=int)

gains = np.array([uav_gains[i] if decs[i] == 1 else bs_gains[i] for i in range(1000)]) # (N, )
print(gains)

In [5]:
import numpy as np 

inv_hess_x = np.array([[ 0.1147015,  -0.1147015,   0.688209  ],
 [-0.1147015,   0.1147015,   0.311791  ],
 [ 0.688209,    0.311791,   -1.87074601]])

grad_x = np.array([-1., -2., 0])

rs = np.dot(inv_hess_x, grad_x)
print(rs)

inv_hess_x = np.array([[ 0.11982215, -0.11982215,  0.465644  ],
 [-0.11982215,  0.11982215,  0.534356  ],
 [ 0.465644,    0.534356,   -2.07657488]])

grad_x = np.array([-1.40090561, -1.44395693, 0])

rs = np.dot(inv_hess_x, grad_x)
print(rs)

inv_hess_x = np.array([[0.11928035, -0.11928035,  0.45505638],
 [-0.11928035,  0.11928035,  0.54494362],
 [ 0.45505638,  0.54494362, -2.07896841]]) 
grad_x = np.array([-1.42419005, -1.42409446, 0])

rs = np.dot(inv_hess_x, grad_x)
print(rs)

[ 0.1147015 -0.1147015 -1.311791 ]
[ 0.0051585  -0.0051585  -1.42391034]
[-1.14020087e-05  1.14020087e-05 -1.42413796e+00]


In [6]:
import numpy as np 

a = np.array([1e-5, 1e-5])
# b = np.array([1.00000495, 1.000000495])

if np.allclose(a, 0, atol=1e-5): 
    print("allclose")
else: 
    print("notclose")

allclose


In [6]:
a = np.array([0, 1])
print(f"a.shape = {a.shape}")

b = a[np.newaxis]
print(f"b = {b}\tb.shape = {b.shape}")

c = np.array([1]) 
# c = c[np.newaxis]
print(f"c = {c}\tc.shape = {c.shape}")

a.shape = (2,)
b = [[0 1]]	b.shape = (1, 2)
c = [1]	c.shape = (1,)


In [13]:
import numpy as np 

freqs1 = np.array([1.01824890e+09, 9.52062760e+08, 9.62805096e+08, 1.03745825e+09,
 1.48488186e+09, 1.02070739e+09, 1.03433882e+09, 1.07679542e+09,
 1.20784196e+09, 9.97309327e+08])

freqs2 = np.array([1.02153349e+09, 9.55435083e+08, 9.88032108e+08, 1.07500226e+09,
  1.61427405e+09, 1.02193454e+09, 1.07655547e+09, 1.12636068e+09,
  1.28778090e+09, 9.98744415e+08])

delta = freqs1 - freqs2
print(delta)

powers1 = np.array([0.06711497, 0.05477767, 0.04590375, 0.05220358, 0.09026404, 0.06880797,
 0.04930643, 0.0530034,  0.06096921, 0.06406872])

powers2 = np.array([0.06734676, 0.05498009, 0.04727716, 0.05445407, 0.1021736,  0.06890176,
  0.05178259, 0.05604995, 0.06649661, 0.06417036])

delta2 = powers1 - powers2 
print(delta2)


t_total1 = np.array([48.46389497, 48.50444874, 51.90314991, 53.21729314, 58.40360614, 48.13211266,
 53.82466166, 54.42345814, 56.57577066, 48.16871117])

t_total2 = np.array([49.19256421, 49.23863258, 53.01633798, 54.39957409, 59.33206324, 48.80953832,
 55.02594205, 55.62759562, 57.70348322, 48.85177917])

delta_t = t_total1.sum() - t_total2.sum()
print(delta_t)

obj1 = 23.05245124756506
obj2 = 23.50953202198276
delta_e = obj1 - obj2 
print(delta_e)


[-3.2845900e+06 -3.3723230e+06 -2.5227012e+07 -3.7544010e+07
 -1.2939219e+08 -1.2271500e+06 -4.2216650e+07 -4.9565260e+07
 -7.9938940e+07 -1.4350880e+06]
[-2.317900e-04 -2.024200e-04 -1.373410e-03 -2.250490e-03 -1.190956e-02
 -9.379000e-05 -2.476160e-03 -3.046550e-03 -5.527400e-03 -1.016400e-04]
-9.580403289999936
-0.457080774417701
