In [4]:
import torch.nn as nn 

model = nn.Linear(2, 3)
params = {k: v.data for k, v in zip(model.state_dict(), model.parameters())}

print(params)
# Calculate the number of parameters 
num_params = sum(param.numel() for param in model.parameters())
print(num_params) # 9 

{'weight': tensor([[-0.0754, -0.0753],
        [-0.6765,  0.5025],
        [-0.2202,  0.6343]]), 'bias': tensor([-0.2950, -0.1803, -0.6243])}
9


In [5]:
import numpy as np 

model1 = nn.Linear(2, 3)
model2 = nn.Linear(2, 3)
model3 = nn.Linear(2, 3)

# Copy model.parameters() to flatten np.array 
def preprocess(model): 
    params = np.array([])
    for v in model.parameters(): 
        params = np.append(params, v.data.numpy())
    return params 

params1 = preprocess(model1)
params2 = preprocess(model2)
params3 = preprocess(model3)

# Avarage (aggregate) the model parameters 
params = np.mean(np.array([params1, params2, params3]), axis=0)
print(params)

# Convert the data back to dictionary of parameters 
params_dict = {}

# load_state_dict ()
# https://pytorch.org/tutorials/beginner/saving_loading_models.html


[-0.01657281 -0.01304539 -0.41262166 -0.12366266  0.03107857 -0.12102356
 -0.0534808  -0.03138488 -0.1824799 ]


In [6]:
c = {'a': 1, 'b': 2, 'c': 3}
d = {}

for k in c.keys(): 
    d[k] = c[k]

print(d)

{'a': 1, 'b': 2, 'c': 3}


In [7]:
x1 = 10 ** (-5)
x2 = 1e-5

print("x1 =", x1)
print("x2 =", x2)

x1 = 1e-05
x2 = 1e-05


In [8]:
from math import exp
from scipy.special import lambertw

t = lambertw(1/(2 * exp(1)))
x = t.real + 1
print(x)


1.157184951483814


In [9]:
import numpy as np 
arr = np.array([5, -1, 2, 4, 2, 3, 7, 0, -1, -4, -3])
k = 5 

idx = np.argpartition(arr, k)[:k]
print(idx)


print(idx[np.where(arr[idx] < 0)])

decs = np.zeros_like(arr)
decs[idx] = 1
print(decs)

[10  9  1  8  7]
[10  9  1  8]
[0 1 0 0 0 0 0 1 1 1 1]


In [3]:
from scipy.special import lambertw
import numpy as np 

tmp = lambertw(1 / (2 * np.exp(1))).real

t = 1 + tmp 
print(t)

t2 = 2 * np.exp(tmp)
print(t2)

t3 = lambertw(-1/(2 * np.exp(1)))
print(f"t3 = {t3}")

t4 = lambertw(-1/(2 * np.exp(1)), k=-1)
print(f"t4 = {t4}")


t4 = (2 * np.exp(t3 + 1) - 1)
print(t4)

1.157184951483814
2.3404240526760884
t3 = (-0.23196095298653444+0j)
t4 = (-2.6783469900166605+0j)
(3.3110704070010053+0j)


In [2]:
import math
import numpy as np 

idx = np.array([i for i in range(1, 10, 1)], dtype=int)
print(idx)
# h_uav = np.zeros_like(idx)
# h_bs = np.zeros_like(idx)
v = 23 

for i in idx:
    eta = 0.1 * i
    x = ((1 - eta)/ (eta * math.log(1 / eta)) - 1) * v / math.log(2)
    h_uav = 2.7 * 1e-11 / x 
    h_bs = 4.38 * 1e-11 / x 
    print("eta = {:.1f}\tx = {:.3f}\th_uav = {:.3e}\t h_bs = {:.3e}".format(eta, x, h_uav, h_bs))

[1 2 3 4 5 6 7 8 9]
eta = 0.1	x = 96.515	h_uav = 2.797e-13	 h_bs = 4.538e-13
eta = 0.2	x = 49.287	h_uav = 5.478e-13	 h_bs = 8.887e-13
eta = 0.3	x = 31.126	h_uav = 8.675e-13	 h_bs = 1.407e-12
eta = 0.4	x = 21.138	h_uav = 1.277e-12	 h_bs = 2.072e-12
eta = 0.5	x = 14.690	h_uav = 1.838e-12	 h_bs = 2.982e-12
eta = 0.6	x = 10.123	h_uav = 2.667e-12	 h_bs = 4.327e-12
eta = 0.7	x = 6.689	h_uav = 4.037e-12	 h_bs = 6.548e-12
eta = 0.8	x = 3.994	h_uav = 6.761e-12	 h_bs = 1.097e-11
eta = 0.9	x = 1.811	h_uav = 1.491e-11	 h_bs = 2.418e-11


In [21]:
import numpy as np 

uav_gains = np.random.randint(0, 10, 5)
bs_gains = np.random.randint(0, 10, 5)

print(uav_gains)
print(bs_gains)
decs = 0

gains = decs * uav_gains + (1 - decs) * bs_gains
print(gains)

[8 2 8 7 3]
[5 0 4 5 3]
[5 0 4 5 3]


In [19]:
import numpy as np 

uav_gains = np.random.randint(0, 100, 1000)
bs_gains = np.random.randint(0, 100, 1000)

decs = np.random.randint(0, 2, 1000, dtype=int)

gains = np.array([uav_gains[i] if decs[i] == 1 else bs_gains[i] for i in range(1000)]) # (N, )
print(gains)

In [5]:
import numpy as np 

inv_hess_x = np.array([[ 0.1147015,  -0.1147015,   0.688209  ],
 [-0.1147015,   0.1147015,   0.311791  ],
 [ 0.688209,    0.311791,   -1.87074601]])

grad_x = np.array([-1., -2., 0])

rs = np.dot(inv_hess_x, grad_x)
print(rs)

inv_hess_x = np.array([[ 0.11982215, -0.11982215,  0.465644  ],
 [-0.11982215,  0.11982215,  0.534356  ],
 [ 0.465644,    0.534356,   -2.07657488]])

grad_x = np.array([-1.40090561, -1.44395693, 0])

rs = np.dot(inv_hess_x, grad_x)
print(rs)

inv_hess_x = np.array([[0.11928035, -0.11928035,  0.45505638],
 [-0.11928035,  0.11928035,  0.54494362],
 [ 0.45505638,  0.54494362, -2.07896841]]) 
grad_x = np.array([-1.42419005, -1.42409446, 0])

rs = np.dot(inv_hess_x, grad_x)
print(rs)

[ 0.1147015 -0.1147015 -1.311791 ]
[ 0.0051585  -0.0051585  -1.42391034]
[-1.14020087e-05  1.14020087e-05 -1.42413796e+00]


In [6]:
import numpy as np 

a = np.array([1e-5, 1e-5])
# b = np.array([1.00000495, 1.000000495])

if np.allclose(a, 0, atol=1e-5): 
    print("allclose")
else: 
    print("notclose")

allclose


In [6]:
a = np.array([0, 1])
print(f"a.shape = {a.shape}")

b = a[np.newaxis]
print(f"b = {b}\tb.shape = {b.shape}")

c = np.array([1]) 
# c = c[np.newaxis]
print(f"c = {c}\tc.shape = {c.shape}")

a.shape = (2,)
b = [[0 1]]	b.shape = (1, 2)
c = [1]	c.shape = (1,)


In [10]:
class PropertyTest: 
    def __init__(self):
        self._num_samples = 0 
        pass

    @property
    def num_samples(self): 
        return self._num_samples 
    
    def abc(self): 
        return (self._num_samples, 123)
        

test = PropertyTest()
test.num_samples
test.abc()

(0, 123)

In [7]:
import math 

L_Lipschitz = 0.4185 # Lipschitz constant of the loss function
gamma_cv = 0.45 # strongly convex constant of the loss function
xi_factor = 0.1 # global gradient factor
epsilon_0 = 5*1e-3 # global accuracy 
epsilon_alpha = 1.1 # alpha factor for decreasing the accuracy

a_0 = 2 * (L_Lipschitz**2) / ((gamma_cv**2) * xi_factor) * math.log(1/epsilon_0) # a = 37.301878506503535
a_alpha = 2 * (L_Lipschitz**2) / ((gamma_cv**2) * xi_factor) * math.log(1/epsilon_alpha) # negative 

print(f"a_0 = {a_0}\ta_alpha = {a_alpha}")

eta = 0.2 

for iter in range(10): 
    an = a_0 + iter * a_alpha
    n = an / (1 - eta)
    print(f"iter = {iter}\tan = {an}\tn = {n}")

a_0 = 91.65029380654791	a_alpha = -1.6486754902552114
iter = 0	an = 91.65029380654791	n = 114.56286725818488
iter = 1	an = 90.00161831629269	n = 112.50202289536585
iter = 2	an = 88.35294282603749	n = 110.44117853254686
iter = 3	an = 86.70426733578228	n = 108.38033416972785
iter = 4	an = 85.05559184552706	n = 106.31948980690882
iter = 5	an = 83.40691635527185	n = 104.25864544408981
iter = 6	an = 81.75824086501663	n = 102.19780108127078
iter = 7	an = 80.10956537476143	n = 100.13695671845178
iter = 8	an = 78.46088988450622	n = 98.07611235563276
iter = 9	an = 76.812214394251	n = 96.01526799281375


In [1]:
import math 

lr0 = 1 
k = 0.99

for t in range(1, 10, 1): 
    lr = lr0 * math.exp(1/(k * t))
    print(f"t = {t}\tlr = {lr} kt = {1/(k*t)} 1 + kt = {1/(1 + k*t)}")

print(math.exp(-k))

t = 1	lr = 2.7458783624599876 kt = 1.0101010101010102 1 + kt = 0.5025125628140703
t = 2	lr = 1.6570692087115697 kt = 0.5050505050505051 1 + kt = 0.33557046979865773
t = 3	lr = 1.400319376534295 kt = 0.3367003367003367 1 + kt = 0.2518891687657431
t = 4	lr = 1.2872720026131113 kt = 0.25252525252525254 1 + kt = 0.20161290322580647
t = 5	lr = 1.2238727325632832 kt = 0.20202020202020202 1 + kt = 0.1680672268907563
t = 6	lr = 1.1833509101421669 kt = 0.16835016835016836 1 + kt = 0.1440922190201729
t = 7	lr = 1.1552307924324114 kt = 0.14430014430014432 1 + kt = 0.12610340479192939
t = 8	lr = 1.1345800996902384 kt = 0.12626262626262627 1 + kt = 0.11210762331838565
t = 9	lr = 1.1187740029938238 kt = 0.1122334455667789 1 + kt = 0.10090817356205853
0.3715766910220457


In [3]:
import math

# alpha = 1.05
# for eps0 in epss:  
#     tmp1 = (eps0**(1/n))
#     tmp2 = tmp1/eps0
#     a = tmp2/ (alpha ** ((n-1)/2))
#     print(f"tmp1 = {tmp1}\ttmp2 = {tmp2}\ta = {a}")
print("----")

epss = [1e-3, 5*1e-4, 1e-4]
n = 151 
aarr = [5, 50, 100, 200, 500]
for eps0 in epss:
    for a in aarr:  
        alpha = (1/a) ** (2/(n-1)) * (1/eps0) ** (2/n)
        print(f"eps0 = {eps0}\ta = {a}\talpha = {alpha}")

----
eps0 = 0.001	a = 5	alpha = 1.0725449423573252
eps0 = 0.001	a = 50	alpha = 1.0401169311848881
eps0 = 0.001	a = 100	alpha = 1.0305484932855355
eps0 = 0.001	a = 200	alpha = 1.0210680791468665
eps0 = 0.001	a = 500	alpha = 1.0086693692850832
eps0 = 0.0005	a = 5	alpha = 1.082437056297306
eps0 = 0.0005	a = 50	alpha = 1.0497099606122333
eps0 = 0.0005	a = 100	alpha = 1.0400532727252205
eps0 = 0.0005	a = 200	alpha = 1.0304854204446572
eps0 = 0.0005	a = 500	alpha = 1.0179723569126287
eps0 = 0.0001	a = 5	alpha = 1.1057591260941642
eps0 = 0.0001	a = 50	alpha = 1.0723268960039312
eps0 = 0.0001	a = 100	alpha = 1.0624621461814947
eps0 = 0.0001	a = 200	alpha = 1.0526881460077167
eps0 = 0.0001	a = 500	alpha = 1.0399054773846865


In [20]:
import numpy as np 
# seed = 42
rng = np.random.default_rng()

def init_location():
    width, height = 20, 100 
    num_users = 10 
    
    dirs = rng.integers(low=0, high=4, size=num_users)
    xs = np.zeros(num_users)
    ys = np.zeros(num_users)

    for i, dir in enumerate(dirs):
        if dir == 0 or dir == 2:
            xs[i] = rng.normal(loc=0, scale=height)
            ys[i] = rng.normal(loc=0, scale=width)
        if dir == 1 or dir == 3: 
            xs[i] = rng.normal(loc=0, scale=width)
            ys[i] = rng.normal(loc=0, scale=height)
 
    return xs, ys, dirs

xs, ys, dirs = init_location()

print(f"xs = {xs}")
print(f"ys = {ys}")
print(f"dirs = {dirs}")

xs = [ -23.35963903  -96.27181825   -1.19812029   20.71485799   50.69282164
   -2.55338168   18.61423769 -132.25663011   10.19063667   -0.41933791]
ys = [-14.89407989   7.13837887  45.29717038 -83.43264913  29.21601405
 133.84483355 -50.61475011 -11.57404895 -91.07975347  20.68710754]
dirs = [0 2 1 1 2 3 3 0 3 3]


In [20]:
import numpy as np 
from scipy.optimize import Bounds 
from scipy.optimize import LinearConstraint
from scipy.optimize import minimize 

a = 0.03482371435133165	
b = 9863.430506596913	
c = 0.05116275624731778	
kappa = 0.09999999999999999
tau = 0.8098728122557564	
# taumin = 0.030631940230047387	
z_min = 0.14503226322827228	
t_min = 0.5

bounds = Bounds([z_min, t_min], [np.inf, np.inf])
linear_constraint = LinearConstraint([a, c], tau, tau)

x0 = np.array([z_min, t_min]) + np.random.rand(2)

def objective(x): 
    z, t = x[0], x[1]
    f0 = a/b * z * (np.exp(1/z) - 1) + kappa * c / (t**2) # (1)
    return f0 

def grad_obj(x): 
    z, t = x[0], x[1]
    grad = np.array([a/b * ((1 - 1/z) * np.exp(1/z) - 1), -2 * kappa * c / (t**3)])
    # grad = grad[:, np.newaxis] # (2, 1)
    return grad 

def hessian(x): 
    z, t = x[0], x[1]
    hess = np.array([[a/b * np.exp(1/z) / (z**3), 0],
                    [0, 6 * kappa * c / (t**4)]]) # (2, 2)
    return hess

res = minimize(objective, x0, method='trust-constr', jac=grad_obj, hess=hessian,
               constraints=linear_constraint, options={'verbose': 1}, bounds=bounds)

res

`gtol` termination condition is satisfied.
Number of iterations: 28, function evaluations: 12, CG iterations: 17, optimality: 3.44e-10, constraint violation: 1.11e-16, execution time: 0.016 s.


 barrier_parameter: 1.0240000000000006e-08
 barrier_tolerance: 1.0240000000000006e-08
          cg_niter: 17
      cg_stop_cond: 1
            constr: [array([0.80987281]), array([ 1.22637542, 14.99461564])]
       constr_nfev: [0, 0]
       constr_nhev: [0, 0]
       constr_njev: [0, 0]
    constr_penalty: 1.0
  constr_violation: 1.1102230246251565e-16
    execution_time: 0.016202926635742188
               fun: 2.821137011210055e-05
              grad: array([-2.05766079e-06, -3.03513432e-06])
               jac: [array([[0.03482371, 0.05116276]]), array([[1., 0.],
       [0., 1.]])]
   lagrangian_grad: array([-3.43976233e-10,  2.34125973e-10])
           message: '`gtol` termination condition is satisfied.'
            method: 'tr_interior_point'
              nfev: 12
              nhev: 10
               nit: 28
             niter: 28
              njev: 10
        optimality: 3.4397623284561033e-10
            status: 1
           success: True
         tr_radius: 111.24296298714

In [63]:
import math
def func(rho, i, n): 
    print(f"rho = {rho}\ti = {i}\tn = {n}")
    epsilon_0 = 5*1e-3 
    lr = 5*1e-3 
    
    eta = 1 - (2* rho**2 * math.log(1/epsilon_0))/n  
    a = rho  
    b = -2
    c = 2/i * math.log2(n/(n - 2*(rho**2)*math.log(1/epsilon_0)))

    # calculate the discriminant
    d = (b**2) - (4*a*c)

    # find two solutions
    sol1 = (-b-math.sqrt(d))/(2*a)
    sol2 = (-b+math.sqrt(d))/(2*a)
    
    # print('The solution are {0} and {1}'.format(sol1,sol2))
    
    gamma_cv1 = sol1/lr
    gamma_cv2 = sol2/lr

    print('eta = {0}\tgamma_cv are {1} and {2}'.format(eta,gamma_cv1,gamma_cv2))

func(rho=1.4, i=30, n=100)
func(rho=1.4, i=20, n=100)
func(rho=1.1, i=30, n=100)
func(rho=1.05, i=30, n=100)

rho = 1.4	i = 30	n = 100
eta = 0.7923059592313171	gamma_cv are 2.2569648939844305 and 283.4573208203013
rho = 1.4	i = 20	n = 100
eta = 0.7923059592313171	gamma_cv are 3.3991440465523146 and 282.3151416677334
rho = 1.1	i = 30	n = 100
eta = 0.8717807197295375	gamma_cv are 1.3245768685607398 and 362.31178676780286
rho = 1.05	i = 30	n = 100
eta = 0.8831721020676158	gamma_cv are 1.1986615349025511 and 379.7537194174784
