In [10]:
import numpy as np 

x = np.ones(shape=5)*2
print(x)
print(x.shape)

[2. 2. 2. 2. 2.]
(5,)


In [7]:
j = np.array(range(5))
print(j)
print(j.shape)

[0 1 2 3 4]
(5,)


In [11]:
y = np.power((j+1), -1.2)
print(y)
print(y.shape)

t = y*x
print(t)
print(t.shape)

[1.         0.43527528 0.26758052 0.18946457 0.14495593]
(5,)
[2.         0.87055056 0.53516104 0.37892914 0.28991187]
(5,)


In [19]:
t = np.array([np.power((j+1), -1.2) for j in range(5)])

print(t)

print(t.shape)

[1.         0.43527528 0.26758052 0.18946457 0.14495593]
(5,)


In [23]:
samples = 5 
classes = 4 
dimensions = 3 

xx = np.ones((samples, dimensions))
b = np.ones(classes)*2
W = np.ones((dimensions, classes)) * 3 

y = np.dot(xx, W) + b 
yy = np.argmax(y, axis=1)
# print(y)

# print(xx)
# print(b)
# print(W)

In [49]:
users = 6 
B = np.ones(shape=(users, 1)) 

#(users, dimensions)
print(B.shape)
# print(B)

mean_y = np.tile(B, reps=dimensions)



# print(mean_x)
# print(mean_x.shape)

(6, 1)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
import torch 

net = torch.nn.Linear(2, 3)
x = torch.rand(4, 2).requires_grad_(True)

loss = net(x).sum() ** 2 
loss.backward()

params_dict = {k: v.data for k, v in zip(net.state_dict(), net.parameters())}
print(params_dict)
print('\n')
grads_dict = {k: v.grad for k, v in zip(net.state_dict(), net.parameters())}

print(grads_dict)

{'weight': tensor([[ 0.6056,  0.3842],
        [ 0.3227,  0.5768],
        [-0.3212, -0.1447]]), 'bias': tensor([-0.5840, -0.2665,  0.0425])}


{'weight': tensor([[-2.8229, -2.4018],
        [-2.8229, -2.4018],
        [-2.8229, -2.4018]]), 'bias': tensor([-5.8902, -5.8902, -5.8902])}


In [18]:
weight = params_dict['weight'].clone()
size = weight.element_size() * weight.nelement()
print(size)


24


In [19]:
for key, val in params_dict.items(): 
    print(key, '\n', val)

weight 
 tensor([[ 0.6056,  0.3842],
        [ 0.3227,  0.5768],
        [-0.3212, -0.1447]])
bias 
 tensor([-0.5840, -0.2665,  0.0425])


In [16]:
import numpy as np 

num_users = 6 

decs = np.array([0, 1, 1, 0, 0, 1])
shape = decs.shape 

print(decs)

uav_gains = np.random.randint(low=0, high=15, size=shape)
print(uav_gains)

bs_gains = np.random.randint(low=0, high=7, size=shape)
print(bs_gains)

gains = np.array([uav_gains[i] if decs[i] == 1 else bs_gains[i] for i in range(num_users)]) 
print(gains)
print(type(gains))

delta_t = 2
ti_penalty = decs * delta_t
print(ti_penalty)
print(type(ti_penalty))


[0 1 1 0 0 1]
[ 7  6  4 12 10  7]
[1 3 5 4 6 1]
[1 6 4 4 6 7]
<class 'numpy.ndarray'>
[0 2 2 0 0 2]
<class 'numpy.ndarray'>


In [1]:
import numpy as np 

f_max = 3
num_users = 6 

freqs = np.ones(num_users) * f_max
print(freqs)

[3. 3. 3. 3. 3. 3.]


In [6]:
a = np.random.randint(3, 7, 6)
b = np.random.randint(1, 10, 6)
print(f"a = {a}\nb = {b}")
print(a < b)

a = [4 4 5 4 6 5]
b = [8 2 3 6 6 8]
[ True False False  True False  True]


In [7]:
decs = np.array([0 if a[i] < b[i] else 1 for i in range(num_users)])
print(decs)

[0 1 1 0 1 0]
