In [47]:
import torch.nn as nn 

model = nn.Linear(2, 3)
params = {k: v.data for k, v in zip(model.state_dict(), model.parameters())}

print(params)
# Calculate the number of parameters 
num_params = sum(param.numel() for param in model.parameters())
print(num_params) # 9 

{'weight': tensor([[ 0.1121, -0.1636],
        [-0.6491, -0.1822],
        [ 0.5718,  0.0618]]), 'bias': tensor([0.6658, 0.5949, 0.5795])}
9


In [64]:
import numpy as np 

model1 = nn.Linear(2, 3)
model2 = nn.Linear(2, 3)
model3 = nn.Linear(2, 3)

# Copy model.parameters() to flatten np.array 
def preprocess(model): 
    params = np.array([])
    for v in model.parameters(): 
        params = np.append(params, v.data.numpy())
    return params 

params1 = preprocess(model1)
params2 = preprocess(model2)
params3 = preprocess(model3)

# Avarage (aggregate) the model parameters 
params = np.mean(np.array([params1, params2, params3]), axis=0)
print(params)

# Convert the data back to dictionary of parameters 
params_dict = {}

# load_state_dict ()
# https://pytorch.org/tutorials/beginner/saving_loading_models.html


[-0.00968184 -0.0276112   0.07457525 -0.07057706  0.40445401  0.04708995
 -0.11704029 -0.32865003 -0.05915562]


In [1]:
c = {'a': 1, 'b': 2, 'c': 3}
d = {}

for k in c.keys(): 
    d[k] = c[k]

print(d)

{'a': 1, 'b': 2, 'c': 3}


In [1]:
x1 = 10 ** (-5)
x2 = 1e-5

print("x1 =", x1)
print("x2 =", x2)

x1 = 1e-05
x2 = 1e-05


In [12]:
from math import exp
from scipy.special import lambertw

t = lambertw(1/(2 * exp(1)))
x = t.real + 1
print(x)


1.157184951483814


In [7]:
import numpy as np 
arr = np.array([5, -1, 2, 4, 2, 3, 7, 0, -1, -4, -3])
k = 5 

idx = np.argpartition(arr, k)[:k]
print(idx)


print(idx[np.where(arr[idx] < 0)])

decs = np.zeros_like(arr)
decs[idx] = 1
print(decs)

[10  9  1  8  7]
[10  9  1  8]
[0 1 0 0 0 0 0 1 1 1 1]


In [2]:
from scipy.special import lambertw
import numpy as np 

tmp = lambertw(1 / (2 * np.exp(1))).real

t = 1 + tmp 
print(t)

t2 = 2 * np.exp(tmp)
print(t2)

t3 = lambertw(-1/(2 * np.exp(1))).real
print(t3.real)

t4 = (2 * np.exp(t3 + 1) - 1)
print(t4)

1.157184951483814
2.3404240526760884
-0.23196095298653444
3.3110704070010053


In [8]:
import math

idx = np.array([i for i in range(1, 10, 1)], dtype=int)
print(idx)
# h_uav = np.zeros_like(idx)
# h_bs = np.zeros_like(idx)

for i in idx:
    eta = 0.1 * i
    x = (1 - eta)/ (eta * math.log(1 / eta)) - 1
    h_uav = 2.7 * 1e-11 / x 
    h_bs = 4.38 * 1e-11 / x 
    print("eta = {:.1f}\tx = {:.3f}\th_uav = {:.3e}\t h_bs = {:.3e}".format(eta, x, h_uav, h_bs))


[1 2 3 4 5 6 7 8 9]
eta = 0.1	x = 2.909	h_uav = 9.283e-12	 h_bs = 1.506e-11
eta = 0.2	x = 1.485	h_uav = 1.818e-11	 h_bs = 2.949e-11
eta = 0.3	x = 0.938	h_uav = 2.878e-11	 h_bs = 4.669e-11
eta = 0.4	x = 0.637	h_uav = 4.238e-11	 h_bs = 6.876e-11
eta = 0.5	x = 0.443	h_uav = 6.099e-11	 h_bs = 9.894e-11
eta = 0.6	x = 0.305	h_uav = 8.850e-11	 h_bs = 1.436e-10
eta = 0.7	x = 0.202	h_uav = 1.339e-10	 h_bs = 2.173e-10
eta = 0.8	x = 0.120	h_uav = 2.243e-10	 h_bs = 3.639e-10
eta = 0.9	x = 0.055	h_uav = 4.947e-10	 h_bs = 8.025e-10
